name: ci

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Ktlint
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ktlintCheck
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test
